### Python and SQL: intro / SQL platforms - 2019 Z


### This material may not be copied or published elsewhere (including Facebook and other social media) without the  permission of the author!

# NumPy
Numpy is an essential Python package for vector and matrix operations. It is fast, flexible, useful for handling large datasets and pseudorandom numbers. It makes a foundation for multiple other packages, including Pandas.

## Creating objects
### Manual filling
Usually when using Numpy as one of multiple libaries, we import it as np (import numpy as np). To increase code readability in this notebook we import all numpy functions directly.

Let us begin with two easiest examples, creating a vector and a matrix.

In [53]:
#import numpy as np
from numpy import *
v = array([1,2,3,4])
print(v, type(v),"shape:", v.shape,"size:",v.size)

M = array([[1,2],[3,4]])
print(M, type(M), M.shape, M.size)

[1 2 3 4] <class 'numpy.ndarray'> shape: (4,) size: 4
[[1 2]
 [3 4]] <class 'numpy.ndarray'> (2, 2) 4


### "zeros", "ones" and "empty"
You rarely want to fill vector/matrix values manually. Usually you would want to initialize it in a different way. Most common options are zeros, ones and empty. Each of these functions requires a shape argument and optionally takes arguments about matrix's type and orientation (default: rows x columns). You can find other ways to create arrays here:
https://docs.scipy.org/doc/numpy/reference/routines.array-creation.html 

In [3]:
print(zeros((3, 4)))
print(ones((3, 4)), float32)
# You cannot foresee what will be used to fill a matrix when using empty.
# Because it is only marginally faster than zeros and ones you should not use it often.
print(empty((3, 4)))

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]] <class 'numpy.float32'>
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


### Convert existing object to a matrix
Sometimes you may want to create a matrix from an existing object. It is good to mention here that changing shape of a matrix is easy and fast even for large matrices. It does not change the way how matrix is stored in memory, just the way how memory is interpreted.

In [3]:
x = list(range(12))
print("List: ", x)
print("numpy matrix:", asarray(x))
print("numpy matrix with a different shape:\n", asarray(x).reshape((3, 4)))

List:  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
numpy matrix: [ 0  1  2  3  4  5  6  7  8  9 10 11]
numpy matrix with a different shape:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### Vector/matrix as range
Reshape method called on an existing matrix does not return its copy. It creates a new "view" of the same data.

Look at the example below, which uses arange - a way to create matrix from a range, which takes arguments analogous to Python's range.

In [7]:
r = arange(0, 23, 2)
print(r)
R = r.reshape((3, 4))
# Alternatively, you can write the line above like this: R = reshape(r, (3, 4))
r[0]=10
r.shape=(3, 4)
print("Changing the value of 'r' also changes the value of 'R'")
print(R)
print(r)

[ 0  2  4  6  8 10 12 14 16 18 20 22]
Changing the value of 'r' also changes the value of 'R'
[[10  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
[10  2  4  6  8 10 12 14 16 18 20 22]


Those interested how matrix implementation works should read the following stackoverflow answer: http://stackoverflow.com/a/22074424 Those very interested may read the documentation https://docs.scipy.org/doc/numpy/reference/internals.html

### Random contents
Numpy allows filling a matrix with random numbers using a given distribution. There are many available distributions: https://docs.scipy.org/doc/numpy/reference/routines.random.html. In every available method if you do not pass a matrix's shape you get one random number returned. Remember that the methods belong to the object random.

In [5]:
print("Single random numbers:")
print(random.random()) # float U~[0,1)]
print(random.normal()) # float N~[0,1)]
print(random.normal(20, 5)) # float N~[20,5)]

print("\nMatrix of a uniform distribution [0,1):")
print(random.random((3, 4))) # float U~[0,1)]
print("\nMatrix of a normal distribution N~(0,1):")
print(random.normal(size=(3, 4))) # float N~(0,1)]
print("\nMatrix of a normal distribution N~(20,5):")
print(random.normal(20, 5, (3, 4))) # float N~(20,5)]

Single random numbers:
0.39923391972589417
1.9808748006404178
18.19675975103865

Matrix of a uniform distribution [0,1):
[[ 0.73084423  0.08538792  0.44894502  0.40983055]
 [ 0.23588411  0.60316313  0.35558514  0.26999324]
 [ 0.89418474  0.894927    0.64148999  0.45561377]]

Matrix of a normal distribution N~(0,1):
[[-0.47280876  0.4499753   0.16759649  0.92744924]
 [-0.7735054   0.35694267  0.13074422  0.62443542]
 [-1.34771498 -1.2934676   0.8296635  -1.01951678]]

Matrix of a normal distribution N~(20,5):
[[ 18.15291898  35.10410506  23.25855334  17.61607905]
 [ 20.86059143  19.0789621   29.13755945  26.68840505]
 [ 25.61408178  23.66263181  17.23144812  27.15415787]]


## Transformation
You have seen basic transformations in examples above. Some additional useful transformation are shown below.

Numpy makes transformations easy. If one of passed dimensions equals -1, you tell numpy to infer the new dimension.

In [14]:
r = arange(0, 12, 1)
print(r)
print(r.reshape((2, -1)))



[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


## Memory addressing and indexing
Numpy creates row-major matrices by default. If you select a part of a two-dimensional matrix using only one dimension, you get the specified row. If you want to select a column, you also have to select all rows (:).

In [55]:
r = arange(0, 12)
r.shape=(3, 4)
print(r)
# Get access to given row
print("Row as vector: ", r[2], "; row's dimension", r[2].shape) # alternatively, r[2, :]
print("Row: ", r[2].reshape(4,1), "; row's dimension", r[2].reshape(4,1).shape) # alternatively, r[2, :]
# Get access to given column
print("Column: ", r[:,2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Row as vector:  [ 8  9 10 11] ; row's dimension (4,)
Row:  [[ 8]
 [ 9]
 [10]
 [11]] ; row's dimension (4, 1)
Column:  [ 2  6 10]


An interesting fact is that if you choose a single row it is a vector (second dimension equals 0). Dimensions (4,) and (4,1) are not the same views. You may see this problem occur during algebraic operations which require a one-dimensional structure (not zero-dimensional).

If you assign values to a part of a matrix, you do not have to care about problems with memory addressing or references. The behavior is as expected.

In [22]:
r[1]=r[2].copy()
print(r)
r[2,1]=100
print(r)

# assign collection of values to given row
rNew= arange(20, 24)
r[2]=rNew.reshape(4,)
print(r)

[[ 0  1  2  3]
 [ 8  9 10 11]
 [ 8  9 10 11]]
[[  0   1   2   3]
 [  8   9  10  11]
 [  8 100  10  11]]
[[ 0  1  2  3]
 [ 8  9 10 11]
 [20 21 22 23]]


You can change values of cells, rows, columns and parts of matrix.

In [9]:
ones1 = ones((4,4))
ones2 = ones((2,2))
print("Large matrix:")
print(ones1)
print("Small matrix:")
print(ones2)
ones1[1:3, 1:3]+=ones2
print("Changed large matrix:")
print(ones1)

Large matrix:
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
Small matrix:
[[ 1.  1.]
 [ 1.  1.]]
Changed large matrix:
[[ 1.  1.  1.  1.]
 [ 1.  2.  2.  1.]
 [ 1.  2.  2.  1.]
 [ 1.  1.  1.  1.]]


# Combining/dividing matrices
These operations are often used. Useful functions for this purpose are concatenate and split. The first name is hard to remember, if you want you may use aliases (vstack and hstack). For the sake of readability, only shapes of newly created matrices are printed.

In [35]:
x = random.randint(0, 12, size=(3, 4))
y = random.randint(0, 12, size=(3, 4))
print("x:",x.shape,"\ny:", y.shape)
print("x\n",x)
print("y\n",y)

print("\nConcatenating vertically (adding new rows):")
print(concatenate((x,y), axis=0).shape, vstack((x,y)).shape)
print(vstack((x,y)))

print("\nConcatenating horizontally (adding new columns):")
print(concatenate((x,y), axis=1).shape, hstack((x,y)).shape)
print(hstack((x,y)))

print("\nSplit returns a list which contains two matrices.")
print(split(x, 2, axis=1)[0].shape, split(x, 2, axis=1)[1].shape)
print("\nYou can only split the x matrix to two halves only by columns, because the number of rows is odd.")
print(split(x, 3, axis=0)[0].shape, split(x, 3, axis=0)[1].shape, split(x, 3, axis=0)[2].shape)

x: (3, 4) 
y: (3, 4)
x
 [[ 7  0  9  8]
 [ 5  4  6 11]
 [ 8  9  2  1]]
y
 [[1 9 5 3]
 [6 2 9 3]
 [6 1 6 0]]

Concatenating vertically (adding new rows):
(6, 4) (6, 4)
[[ 7  0  9  8]
 [ 5  4  6 11]
 [ 8  9  2  1]
 [ 1  9  5  3]
 [ 6  2  9  3]
 [ 6  1  6  0]]

Concatenating horizontally (adding new columns):
(3, 8) (3, 8)
[[ 7  0  9  8  1  9  5  3]
 [ 5  4  6 11  6  2  9  3]
 [ 8  9  2  1  6  1  6  0]]

Split returns a list which contains two matrices.
(3, 2) (3, 2)

You can only split the x matrix to two halves only by columns, because the number of rows is odd.
(1, 4) (1, 4) (1, 4)


## Variable types
All available numpy data types are shown here: https://docs.scipy.org/doc/numpy/user/basics.types.html. Fortunately,
numpy allows for easy typecasting. However, if running time and/or memory efficiency are important, you should declare the right type at the beginning. Remember that choosing a different type than default float64 may cause problems. If you make a mistake you may create a "nuclear Gandhi" (http://knowyourmeme.com/memes/nuclear-gandhi).

In [9]:
L = array([1, 2, 2.5, -1, -1.25, 32764, 4294961294, 18446744073709541613])
print(L)
print(L.dtype)
print(L.astype(int))

print(L.astype(uint))
print()
print(L.astype(int8))
print()
print(L.astype(uint8))

[  1.00000000e+00   2.00000000e+00   2.50000000e+00  -1.00000000e+00
  -1.25000000e+00   3.27640000e+04   4.29496129e+09   1.84467441e+19]
float64
[          1           2           2          -1          -1       32764
 -2147483648 -2147483648]
[         1          2          2 4294967295 4294967295      32764
 4294961294          0]

[ 1  2  2 -1 -1 -4  0  0]

[  1   2   2 255 255 252   0   0]


## Descriptive statistics
Functions used in descriptive statistics are implemented in a standard and efficient way. The full list is available here: https://docs.scipy.org/doc/numpy/reference/routines.statistics.html. A few examples are shown below.

In [12]:
r = arange(0, 12)
r.shape=(3, 4)
print(r)
print(amin(r))
#min values per column
print(amin(r, axis=0))
#min values per row
print(amin(r, axis=1))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
0
[0 1 2 3]
[0 4 8]


In [13]:
x = random.normal(size=(100, 100))
hist = histogram(x, bins=10)
# length of a list of counts in an interval equals the number of bins
print(hist[0])
# length of a list of interval's boundaries equals the number of bins + 1
print(hist[1])

[   3   51  336 1305 2727 2997 1841  603  127   10]
[-4.15216489 -3.35307711 -2.55398933 -1.75490155 -0.95581377 -0.15672598
  0.6423618   1.44144958  2.24053736  3.03962514  3.83871293]


## Sorting
Sorting is an operation used quite often. It is important to see a difference between sorting in place and sorting a copy. It may be surprising that numpy does not have implemented sorting in descending order by default. You have to flip a sorted matrix.

In [14]:
x = random.randint(0, 12, size=(3, 4))
print(x)
print("np.sort returns a copy of an object.")

print("Sorting by column means sorting rows -> axis=0")
print(sort(x, axis=0))
print(flipud(sort(x, axis=0)))

print("Sorting by row means sorting columns -> axis=1")
print(sort(x, axis=1))
print(fliplr(sort(x, axis=1)))

print("\nSorting in place is fully analogous:")
x.sort(axis=0)
print(x)
x.sort(axis=1)
print(x)

[[ 3  2  3 11]
 [ 3  1  1  1]
 [10  9  9 10]]
np.sort returns a copy of an object.
Sorting by column means sorting rows -> axis=0
[[ 3  1  1  1]
 [ 3  2  3 10]
 [10  9  9 11]]
[[10  9  9 11]
 [ 3  2  3 10]
 [ 3  1  1  1]]
Sorting by row means sorting columns -> axis=1
[[ 2  3  3 11]
 [ 1  1  1  3]
 [ 9  9 10 10]]
[[11  3  3  2]
 [ 3  1  1  1]
 [10 10  9  9]]

Sorting in place is fully analogous:
[[ 3  1  1  1]
 [ 3  2  3 10]
 [10  9  9 11]]
[[ 1  1  1  3]
 [ 2  3  3 10]
 [ 9  9 10 11]]


You may wonder if flipping a matrix is faster than multiplying it by -1 two times. As you can see, the difference is small.

In [15]:
# Create a large matrix, so that possible differences are significant:
x = random.normal(size=(1000, 1000))
%timeit flipud(sort(x, axis=0))
%timeit (-1*sort(-x, axis=0))

33.2 ms ± 609 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
36.5 ms ± 875 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


Sometimes you may want to know what are the sorted indices of the matrix.

In [16]:
x = random.randint(0, 12, size=(3, 4))
print(x)
print(argsort(x, axis=0))
print(argsort(x, axis=1))

[[ 8  3  9  1]
 [ 6  1  1  6]
 [ 5 11  1  7]]
[[2 1 1 0]
 [1 0 2 1]
 [0 2 0 2]]
[[3 1 0 2]
 [1 2 0 3]
 [2 0 3 1]]


## Algebra and other functions
Numpy has many mathematical, algebraic etc. functions built in. You will see a few examples below. Ability to find a function you need in the documentation is a crucial skill. Not only you see if a function is implemented, but also you know how the implementation works.

Using the example of mathematical functions you will see how important it is to use built-in functions whenever possible.

* Mathematical functions: https://docs.scipy.org/doc/numpy/reference/routines.math.html
* Algebraic functions: https://docs.scipy.org/doc/numpy/reference/routines.linalg.html
* Other groups of functions: https://docs.scipy.org/doc/numpy/reference/index.html

In [17]:
M = arange(0, 4)
N = arange(1, 5)
M.shape=(-1)
N.shape=(-1)
print(M)
print(N)
print("Multiplying vectors:")
print(dot(M,N))

print("\nMatrices")
M = arange(0, 4)
N = arange(1, 5)
M.shape=(2, 2)
N.shape=(2, 2)
print(M)
print(N)
print("\nMultiplying matrices:")
print(dot(M,N))
print("\nInversing matrices:")
print(linalg.inv(M))

[0 1 2 3]
[1 2 3 4]
Multiplying vectors:
20

matrices
[[0 1]
 [2 3]]
[[1 2]
 [3 4]]

Multiplying matrices:
[[ 3  4]
 [11 16]]

Inversing matrices:
[[-1.5  0.5]
 [ 1.   0. ]]


Compare how fast a simple operation using a built-in numpy function is compared to solving the same problem using Python alone.

In [40]:
import math
x = random.normal(size=(10000, 1))
print("Max:")
%timeit -n 100 max(x)
%timeit -n 100 x.max()

print("Sin:")
%timeit -n 100 [math.sin(z) for z in x]
%timeit -n 100 sin(x)

print("Mean:")
%timeit -n 100 mean(x)
%timeit -n 100 x.mean()

Max:
11.2 ms ± 541 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
15.6 µs ± 2.37 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
Sin:
6.4 ms ± 262 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
56.3 µs ± 1.77 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
Mean:
26.7 µs ± 4.43 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
21.7 µs ± 415 ns per loop (mean ± std. dev. of 7 runs, 100 loops each)


As you can see a simple functiom max is over a thousand times\* faster in numpy. sin is over 10 times faster, the difference for a mean is only 10-20%.

\* When running the cell for the first time you may see a message: "The slowest run took 4.07 times longer than the fastest. This could mean that an intermediate result is being cached.". It means that the max function is even slower in practice, as the best 3 results are probably using cache.

## Vectorize
Sometimes you may want to perform operations which are impossible to define using numpy functions. In this case you may rewrite a function to a vector "numpy" version. It is not perfect, but may often save time.

In [46]:
def newFunc(x):
    if x >= 0.5:
        return x
    else:
        return 0.0
x = random.normal(size=(1000000, 1))
newFuncV = vectorize(newFunc)
#check performance of vectorized function
%timeit y=newFuncV(x)
y=x.copy()

351 ms ± 7.59 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [50]:
#check performance of alternative approach
%%timeit
 for i in range(y.shape[0]):
    if y[i]<0.5:
        y[i]=0
##%timeit newFuncSlow(y)

2.58 s ± 75.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


As you can see, a simple change may make the code visibly faster. In practice, optimisations like this are significant only when you use really large datasets.